### ISSUE TITLE
Proposal of easy way to run application

### ISSUE THREAD

**Issue by yoshikawaa** [terasoluna-batch/v5-sample#1]
## Description
At [3.1.2. プロジェクトの作成](https://terasoluna-batch.github.io/guideline/5.0.0.RELEASE/ja/single_index.html#Ch03_CreateProject_HowToCreate)
```console
$ mvn clean dependency:copy-dependencies -DoutputDirectory=lib package
$ java -cp 'lib/*:target/*' org.springframework.batch.core.launch.support.CommandLineJobRunner \
    META-INF/jobs/job01/job01.xml job01
```
It is hard for the developer to input these commands every time.
And `java` command is  not work on Windows Command Prompt, due to the difference in class path grammar. (**Many Japanese developers use Windows**)

## Possible Solutions
One of easy way is using `exec-maven-plugin`.
Configure pom.xml as follows:

* properties
```xml
<exec-maven-plugin.version>1.6.0</exec-maven-plugin.version>
```
* pluginManagement
```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>${exec-maven-plugin.version}</version>
</plugin>
```
* plugins
```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <configuration>
        <mainClass>org.springframework.batch.core.launch.support.CommandLineJobRunner</mainClass>
    </configuration>
</plugin>
```

Easily build and run as follows:
```console
$ mvn clean package
$ mvn exec:java -Dexec.arguments=META-INF/jobs/job01/job01.xml,job01
```

If the job you want to execute is fixed, configure and more easily run as follows:
* plugins
```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <configuration>
        <mainClass>org.springframework.batch.core.launch.support.CommandLineJobRunner</mainClass>
        <arguments>
            <argument>META-INF/jobs/job01/job01.xml</argument>
            <argument>job01</argument>
        </arguments>
    </configuration>
</plugin>
```
```console
$ mvn exec:java
```

How do you think?

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
We discussed this matter in the team, but the execution method of the job should be consistent with the description introduced in the guideline, and the guideline selects a job execution method that can withstand production operation.

In the case of Windows, the `.bat` file, and in the case of Linux, the `.sh` file can be used to describe the body of the command and the class path.
