### ISSUE TITLE
pom error on IntelliJ IDEA

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-sample#2]
## Description
I've imported a generated project using maven archetype into IntelliJ IDEA. Then IDE will report following errors at pom.xml. (Note: The Maven build will be succeed)

* Cannot resolve symbol 'exclude-property' at maven-jar-plugin
* Cannot resolve symbol 'exclude-log' at maven-jar-plugin

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <configuration>
        <excludes>
            <exclude>${exclude-property}</exclude> <!-- ### This !! ### -->
            <exclude>${exclude-log}</exclude> <!-- ### This !! ### -->
        </excludes>
    </configuration>
</plugin>
```

Cause-By...

Has been removed `<exclude-property/>` and `<exclude-log/>` in generated project as follow:

```xml
<profile>
    <id>IncludeSettings</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <properties>
    </properties>
</profile>
```

These properties are exist at the `pom.xml` on GitHub.
 
## Possible Solutions
No idea yet.

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
Fixed so that no error occurs even when using IntelliJ IDEA.
This fix is supported since 5.0.1.RELEASE.
