### ISSUE TITLE
<context:annotation-config/> is redundant at job01.xml

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-sample#4]
## Description
`<context:annotation-config/>` is define at `job01.xml`. I think it is redundant because `<context:component-scan>` include same role with  `<context:annotation-config/>`.

## Possible Solutions

Remove `<context:annotation-config/>` in `job01.xml`.

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
As you pointed out, it was deleted because it is redundant.
This is supported since 5.0.4.RELEASE.
