### ISSUE TITLE
Suggest to change filename of 'async-batch-daemon.polling-stop-file-path'

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-sample#5]
## Description
Current setting is `/tmp/end-async-batch-daemon` as follow:

```properties
async-batch-daemon.polling-stop-file-path=/tmp/end-async-batch-daemon
```

Why file name prefix is `end` ? 
I prefer `stop` rather than `end` because property key include `stop`. 

What do you think ?

## Possible Solutions
Change to `/tmp/stop-async-batch-daemon` as follow:

```properties
async-batch-daemon.polling-stop-file-path=/tmp/stop-async-batch-daemon
```

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
I revised it as suggested.
This is supported since 5.0.4.RELEASE.
