### ISSUE TITLE
Repository for https

### ISSUE THREAD

**Issue by vekee** [terasoluna-batch/v5-sample#7]
## Description
build error at maven 3.6.3

## Possible Solutions
pom.xml
<url>http://repo1.maven.org/maven2/</url>
Change "http" to "https".

## Affects Version/s
* 5.2.1.RELEASE

**Comment by takahashihrzg** [comment]
Thanks for your report.

We have resolved this issue in 5.3.0.RELEASE.
Please use 5.3.0.RELEASE.

https://github.com/terasoluna-batch/v5-sample/tree/5.3.0.RELEASE
