### ISSUE TITLE
sample run error

### ISSUE THREAD

**Issue by vekee** [terasoluna-batch/v5-sample#8]
## Description
java -cp 'lib/*;target/*'  org.springframework.batch.core.launch.support.CommandLineJobRunner  META-INF/jobs/job01.xml job01

```v5-sample-5.2.x/terasoluna-batch-blankproject/
MacBook:terasoluna-batch-blankproject duan$ java -cp 'lib/*;target/*'  org.springframework.batch.core.launch.support.CommandLineJobRunner  META-INF/jobs/job01.xml job01
エラー: メイン・クラスorg.springframework.batch.core.launch.support.CommandLineJobRunnerが見つからなかったかロードできませんでした
```

## Possible Solutions
Add a sample excute java is a better way maybe. 
```
public class excute {
	public static void main(String[] args) throws Exception {
		CommandLineJobRunner.main(new String[] {"META-INF/jobs/job01.xml","job01"});
	}
}
```

## Affects Version/s
* 5.2.1.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
Hi, vekee.

Thank you for your reporting.

We found the README wrong.
If you use xsh(e.g.: bash, zsh), please replace the class path delimiter:“;” with “:”, see below.

* https://terasoluna-batch.github.io/guideline/5.1.1.RELEASE/en/single_index.html#Ch03_CreateProject_BuildAndExec_BuildPerEnv_AppExecution
3.1.6.2.1. Execution of application Bash(Unix, Linux, …​)

We will correct the README, and fix on next release.
